// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_LC_Ms8HSoveVF4RAVtkOn2V21536sM',
    appId: '1:718532286870:web:93186128f2054f298065b7',
    messagingSenderId: '718532286870',
    projectId: 'gamehub-78bfc',
    authDomain: 'gamehub-78bfc.firebaseapp.com',
    storageBucket: 'gamehub-78bfc.appspot.com',
    measurementId: 'G-G6PVWMX7QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mXnfzPNI04T3F1NEIJ9jMimyNMR3DbU',
    appId: '1:718532286870:android:25847ba7c87d87d48065b7',
    messagingSenderId: '718532286870',
    projectId: 'gamehub-78bfc',
    storageBucket: 'gamehub-78bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KW6eFuMGpFS2-NqcNYSuqIRlQct2a8k',
    appId: '1:718532286870:ios:d07e56b561d687e88065b7',
    messagingSenderId: '718532286870',
    projectId: 'gamehub-78bfc',
    storageBucket: 'gamehub-78bfc.appspot.com',
    iosBundleId: 'com.example.procecto2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6KW6eFuMGpFS2-NqcNYSuqIRlQct2a8k',
    appId: '1:718532286870:ios:a70bb484161f58768065b7',
    messagingSenderId: '718532286870',
    projectId: 'gamehub-78bfc',
    storageBucket: 'gamehub-78bfc.appspot.com',
    iosBundleId: 'com.example.procecto2.RunnerTests',
  );
}
