name: procecto2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  rxdart: ^0.27.7
  eva_icons_flutter: ^3.1.0
  url_launcher: ^6.2.4
  http: ^1.1.0
  provider: ^6.0.5
  bottom_navy_bar: ^6.0.0
  flutter_vector_icons: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.3.7
  page_indicator: ^0.4.1
  sleek_circular_slider: ^2.0.1
  youtube_player_flutter: ^9.0.0
  intl: ^0.17.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_native_splash:
  #android: true
  ios: true
  color: "#6eb6ff"
  image: "assets/images/iconGB.png"
  
  android_12:
    color: "#6eb6ff"
    image: "assets/images/iconGB.png"
    image_dark: "assets/images/iconGB.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconGB.png"   #"assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/iconGB.png"
  adaptive_icon_background: "#6eb6ff"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default_avatar.jpg
    - assets/images/gamehub.png
    - assets/images/gamehubFondo.png
    - assets/images/gamehubNuevo.png
    - assets/images/videoError.jpg
    - assets/images/loading_image.gif
    - assets/images/twitch_logo.png
    - assets/images/game_images/rpg.jpg
    - assets/images/game_images/adventure.jpeg
    - assets/images/game_images/arcade.avif
    - assets/images/game_images/fighting.jpg
    - assets/images/game_images/puzzle.jpg
    - assets/images/game_images/racing.jpg
    - assets/images/game_images/shooter.jpg
    - assets/images/game_images/simulation.png
    - assets/images/game_images/sports.jpeg
    - assets/images/game_images/visual.png
    - assets/images/game_images/indie.webp
    - assets/images/game_images/music.png
    - assets/images/game_images/platformer.jpg
    - assets/images/game_images/strategy.webp
    - assets/images/platform_images/mobile.jpg
    - assets/images/platform_images/pc.jpg
    - assets/images/platform_images/ps2.png
    - assets/images/platform_images/ps3.jpg
    - assets/images/platform_images/ps4.webp
    - assets/images/platform_images/ps5.webp
    - assets/images/platform_images/xbox.jpg
    - assets/images/platform_images/psp.jpg
    - assets/images/platform_images/wii.webp
    - assets/images/platform_images/switch.avif
    - assets/images/platform_images/3ds.jpg
    - assets/images/platform_images/n64.webp
    - assets/images/platform_images/ds.jpg
    - assets/images/platform_images/psp.jpg
    - assets/images/platform_images/xbox360.webp
    - assets/images/platform_images/ps1.webp
    - assets/images/franchise_images/res.jpg
    - assets/images/franchise_images/call.jpg
    - assets/images/franchise_images/fallout.jpg
    - assets/images/franchise_images/fifa.jpg
    - assets/images/franchise_images/gt.jpg
    - assets/images/franchise_images/gta5.jpg
    - assets/images/franchise_images/mario.webp
    - assets/images/franchise_images/final.webp
    - assets/images/franchise_images/ass.webp
    - assets/images/franchise_images/sims.jpg
    - assets/images/franchise_images/star.jpg
    - assets/images/franchise_images/zelda.jpeg
    - assets/images/franchise_images/silent.jpg
    - assets/images/franchise_images/monster.jpg
    - assets/images/franchise_images/tomb.avif
    - assets/images/franchise_images/nba.jpg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
